trigger:
  - main

variables:
  - group: secretVariables

pool:
  vmImage: ubuntu-latest

steps:

# Replace Tokens by Secrets for Application Config
# Build the code & run test cases
# Build the Dockerfile, tag and & push to ACR

  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace tokens'
      inputs:
        targetFiles: |
          **/application.properties
        actionOnMissing: 'log warning'
