apiVersion: v1
kind: Pod
metadata:
  name: nginx-privileged
  labels:
    department: csu
    owner: agraj
spec:
  containers:
    - name: nginx-privileged
      image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
      securityContext:
        privileged: true