apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-aks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-aks
  template:
    metadata:
      labels:
        app: spring-boot-aks
    spec:
      containers:
        - name: app
          image: $(ACR_LOGIN_SERVER)/$(ACR_REPO_NAME):$(Build.BuildNumber)
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: springsecret
                key: url
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: springsecret
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: springsecret
                key: password
          imagePullPolicy: Always