apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-aks
  namespace: spboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-aks
  template:
    metadata:
      labels:
        app: spring-boot-aks
        namespace: spboot-app
        aadpodidbinding: spboot-pod-identity
        department: csu
        owner: agrajm
    spec:
      containers:
        - name: app
          image: spbootacr2021am.azurecr.io/spring-boot-aks:v1.0.3
          ports:
          - containerPort: 8080
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: spboot-svc
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-aks
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080